# Generated by Django 2.2 on 2020-07-22 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='date_end',
            field=models.DateField(blank=True, null=True, verbose_name='Дата выполнения'),
        ),
    ]
