# Generated by Django 2.2 on 2020-07-22 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_auto_20200722_1013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='date_end',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='Дата выполнения'),
        ),
    ]
