# Generated by Django 2.2 on 2020-07-26 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_auto_20200722_1033'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='full_description',
            field=models.TextField(blank=True, default=None, max_length=3000, null=True, verbose_name='Полное описание'),
        ),
    ]
