# Generated by Django 2.2 on 2020-08-09 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_auto_20200809_1726'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='types',
            new_name='types_set',
        ),
    ]
