# Generated by Django 2.2 on 2020-08-09 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0007_auto_20200809_1836'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='types_set',
            new_name='types',
        ),
    ]
