# Generated by Django 2.2 on 2020-08-21 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0011_projects'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projects',
            options={'verbose_name': 'Проект', 'verbose_name_plural': 'Проекты'},
        ),
        migrations.RenameField(
            model_name='projects',
            old_name='summary',
            new_name='name',
        ),
    ]
